language: python
python:
  - "2.7"
install: 
    - "pip install -r requirements.txt"
    - "pip install -r requirements-test.txt"
script: 
    - "coverage run --source=egasub setup.py test"
after_success:
    coveralls
